### ISSUE TITLE
关于视觉上的建议

### ISSUE THREAD

**Issue by Silver-Pupil** [GashByte/ICora#1]
1.希望恢复到1.2时候的字体，目前的字体有锯齿感
2.软件左侧的字体有些小
3.友商论坛旁边可以放一个图标提示用户会弹出网页，类似附件这种
![QQ截图20230127201558](https://user-images.githubusercontent.com/103412959/215086130-a9f3f998-5851-430d-be5c-9e6ce628c7fe.png)

**Comment by GashByte** [comment]
感谢您的反馈 我们会吸取您的教训 然后开发出让您们更佳满意的原神工具箱！
