### ISSUE TITLE
空壳CLibrary检测

### ISSUE THREAD

**Issue by zou-ce** [GashByte/ICora#11]
![9O8BJ18FJ0FN_CI386D326Q](https://user-images.githubusercontent.com/120785528/215266224-de7c2b58-51e3-44d4-96df-84e5be6346ce.png)

**Comment by GashByte** [comment]
开始游戏时才可以检测 如果你是1.3.10Release版本 现在存有问题 CLDownloader路径是旧版的路径 已在源码修复
